### ISSUE TITLE
 Parse config.yaml error 'RISKIQ'

### ISSUE THREAD

**Issue by Bronya-Rayi** [TophantTechnology/ARL#379]
docker方式启动的时候，新配置文件解析有点问题，会报错
```bash
arl_web      | [2022-08-29 17:57:55 +0800] [29] [INFO] Worker exiting (pid: 29)
arl_web      | Parse config.yaml error 'RISKIQ'
arl_scheduler | Parse config.yaml error 'RISKIQ'
arl_web      | [2022-08-29 17:57:56 +0800] [31] [INFO] Worker exiting (pid: 31)
arl_web      | Parse config.yaml error 'RISKIQ'
arl_web      | [2022-08-29 17:57:56 +0800] [35] [INFO] Booting worker with pid: 35
arl_web      | [2022-08-29 17:57:56 +0800] [30] [INFO] Worker exiting (pid: 30)
arl_web      | Parse config.yaml error 'RISKIQ'
```
需要再加上以下配置之后才能运行：
```yaml
RISKIQ:
  EMAIL: "n1un1u2019@qq.com"
  KEY: "03da3c29cce5152a536bae332f7b03a288154b37a13b93921225d3ade49c9b4c"
```
