### ISSUE TITLE
xxx包含在系统黑名单中

### ISSUE THREAD

**Issue by m4ra7h0n** [TophantTechnology/ARL#760]
<img width="963" alt="image" src="https://github.com/TophantTechnology/ARL/assets/71647398/cbed9fc6-0797-4eaf-bef6-750e61a6c992">   

我将config.yaml中的黑名单注释掉仍然不行。   

```
ARL:
  AUTH: true
  #API 认证key, 可以访问api/doc查看文档
  API_KEY: ""
  BLACK_IPS:
    - 127.0.0.0/8
    - 0.0.0.0/8
    - 172.16.0.0/12
    - 100.64.0.0/10
    # - 10.0.0.0/8
    # - 192.168.0.0/16
  ## 禁止域名，不可为空数组
  FORBIDDEN_DOMAINS:
    - abc.com
    #- edu.cn
    #- org.cn
    #- gov.cn
```
